name: Code Quality

on:
  push:
    branches:
      - '*'
  pull_request:


jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: |
          npm run lint
          npm run prettier

      - name: Build website
        run: npm run build
